# Generated by Django 2.2.1 on 2019-08-28 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=3)),
                ('number', models.CharField(default='', max_length=3)),
                ('title', models.CharField(default='', max_length=120)),
                ('offered', models.CharField(default='', max_length=120)),
                ('scheduleType', models.CharField(default='', max_length=120)),
                ('workload_hours', models.IntegerField(default=10)),
                ('catalogDescription', models.CharField(default='', max_length=5000)),
                ('prerequisites', models.CharField(default='', max_length=120)),
                ('objective', models.CharField(default='', max_length=120)),
                ('topic', models.CharField(default='', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='courses_per_semester_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='hours_per_semester_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a importance level (e.g. tier1)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Knowledge Area (e.g. AL)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an Outcome', max_length=200)),
                ('importance', models.ManyToManyField(help_text='Select a importance level', to='polls.Importance')),
            ],
        ),
        migrations.CreateModel(
            name='xml_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_text', models.TextField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Topic', max_length=200)),
                ('importance', models.ManyToManyField(help_text='Select a importance level', to='polls.Importance')),
            ],
        ),
        migrations.CreateModel(
            name='SubKnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Sub Knowledge Area', max_length=6)),
                ('summary', models.TextField(help_text='Name of Class', max_length=1000)),
                ('outcome', models.ManyToManyField(help_text='Enter an Outcome', to='polls.Outcome')),
                ('topic', models.ManyToManyField(help_text='Enter a Topic', to='polls.Topic')),
            ],
        ),
    ]
