# Generated by Django 2.2.1 on 2019-06-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Importance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a importance level (e.g. tier1)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Knowledge Area (e.g. AL)', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MyModelName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_field_name', models.CharField(help_text='Enter field documentation', max_length=20)),
            ],
            options={
                'ordering': ['-my_field_name'],
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an Outcome', max_length=200)),
                ('importance', models.ManyToManyField(help_text='Select a importance level', to='polls.Importance')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Topic', max_length=200)),
                ('importance', models.ManyToManyField(help_text='Select a importance level', to='polls.Importance')),
            ],
        ),
        migrations.CreateModel(
            name='SubKnowledgeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a Sub Knowledge Area', max_length=6)),
                ('summary', models.TextField(help_text='Name of Class', max_length=1000)),
                ('outcome', models.ManyToManyField(help_text='Enter an Outcome', to='polls.Outcome')),
                ('topic', models.ManyToManyField(help_text='Enter a Topic', to='polls.Topic')),
            ],
        ),
    ]
