# Generated by Django 2.2.1 on 2019-08-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190828_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses_f',
            name='workloadhours',
            field=models.IntegerField(default=0),
        ),
    ]
