# Generated by Django 2.2.1 on 2019-09-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190828_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses_f',
            name='number',
        ),
        migrations.RemoveField(
            model_name='courses_f',
            name='subject',
        ),
        migrations.AddField(
            model_name='courses_f',
            name='course',
            field=models.CharField(default='', max_length=6),
        ),
    ]
