# Generated by Django 2.2.1 on 2019-06-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_xml_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xml_output',
            name='output_text',
        ),
    ]
