# Generated by Django 2.2.1 on 2019-09-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190904_2301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='xml_output',
        ),
    ]
