# Generated by Django 2.2.1 on 2019-06-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_xml_output_output_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml_output',
            name='output_text',
            field=models.TextField(max_length=10000),
        ),
    ]
