# Generated by Django 2.2.1 on 2019-09-05 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_delete_xml_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModelName',
        ),
    ]
