# Generated by Django 2.2.1 on 2019-06-25 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190625_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml_output',
            name='output_text',
            field=models.TextField(max_length=1000000),
        ),
    ]
