# Generated by Django 2.2.1 on 2019-09-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_delete_mymodelname'),
    ]

    operations = [
        migrations.CreateModel(
            name='schedule_f',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default='', max_length=6)),
                ('section_number', models.CharField(default='', max_length=1)),
                ('start_time', models.CharField(default='', max_length=7)),
                ('end_time', models.CharField(default='', max_length=7)),
                ('day', models.CharField(default='', max_length=1)),
                ('buildingroom', models.CharField(default='', max_length=8)),
                ('max', models.CharField(default='', max_length=3)),
                ('instructor', models.CharField(default='', max_length=9)),
            ],
        ),
    ]
