# Generated by Django 2.2.1 on 2019-06-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190625_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='hours_per_semester_funct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours_per_semester_text', models.CharField(max_length=200)),
            ],
        ),
    ]
