# Generated by Django 2.2.1 on 2019-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190625_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours_per_semester_funct',
            name='hours_per_semester_text',
            field=models.TextField(max_length=20000),
        ),
    ]
