# Generated by Django 2.2.1 on 2019-06-26 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20190625_2246'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hours_per_semester_funct',
            new_name='hours_per_semester_f',
        ),
    ]
