# Generated by Django 2.2.1 on 2019-08-14 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190626_2322'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hours_per_semester_f',
            name='hours_per_semester_text',
        ),
    ]
