# Generated by Django 2.2.1 on 2019-08-14 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_remove_hours_per_semester_f_hours_per_semester_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='say_something',
        ),
    ]
